apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: book001.azurecr.io/book_catalog:v1
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: postgresql://week007_user:pKv4bRACzHRmeYxB5KJcQYXgNUbw0tlr@dpg-crm5git6l47c73eqn6f0-a.oregon-postgres.render.com/week007

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: book001.azurecr.io/inventory_management:v1
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: postgresql://week007_user:pKv4bRACzHRmeYxB5KJcQYXgNUbw0tlr@dpg-crm5git6l47c73eqn6f0-a.oregon-postgres.render.com/week007

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  
